#!/usr/bin/env bash
# Deploy the RINGO 3D web client to S3 + CloudFront.
#   ./scripts/deploy-web.sh
set -euo pipefail
cd "$(dirname "$0")/.."

BUCKET=ringo3d-web-352154386127-us-east-2
DIST_ID=E1O9VORKDZL4G2
WS_URL=wss://o2l49t9p86.execute-api.us-east-2.amazonaws.com/prod

BUILD=build/web
rm -rf "$BUILD"
mkdir -p "$BUILD"
cp -r public/* "$BUILD/"

# Production config: the API Gateway WebSocket endpoint for online play.
cat > "$BUILD/js/config.js" <<EOF
// Generated by scripts/deploy-web.sh — do not edit by hand.
window.RINGO_WS_URL = $( [ "$WS_URL" = null ] && echo null || echo "'$WS_URL'" );
EOF

# no-cache = browsers must revalidate before reusing a cached copy. Without
# it they cache heuristically and can keep running old game rules for hours
# (four-corners didn't work vs. the computer the night it shipped). CloudFront
# still caches at the edge; the invalidation below refreshes it on deploy.
aws s3 sync "$BUILD/" "s3://$BUCKET/" --delete --cache-control no-cache
aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths '/*' \
  --query 'Invalidation.Id' --output text
echo "Deployed → https://ringo3d.beelinemicrosystems.com"
